### ISSUE TITLE
The package-lock.json file was created with an old version of npm

### ISSUE THREAD

**Issue by MelinaDevAdmin** [OfficeDev/microsoft-teams-apps-survey#16]
I am deploying this template and I keep receiving errors after the npm install

ven if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\User01\\CodeUser01\\microsoft-teams-apps-survey-main\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\graceful-fs\polyfills.js:299:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User01\\CodeUser01\\microsoft-teams-apps-survey-main\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\User01\CodeUser01\microsoft-teams-apps-survey-main\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

Please advise.

**Comment by MelinaDevAdmin** [comment]
Any updates?

**Comment by rozzamozza** [comment]
Same error here. Trying to work out if we need python install, regenerate package-lock file from scratch.
